### ISSUE TITLE
Crash when connecting to server with latest fabric and WAYLA

### ISSUE THREAD

**Issue by dmodoomsirius** [Pannoniae/wayla#1]
crash when connecting to server
https://gist.github.com/dmodoomsirius/dbf2a2219aa2059f0cb5a8a177ea5d3e

https://github.com/Pannoniae/wayla/blob/master/src/main/java/net/panno/wayla/mixin/GUIMixin.java#L13-L24

**Comment by Pannoniae** [comment]
Looking into it.

**Comment by Pannoniae** [comment]
Fixed with 2.5.0, please download it.
